countrycode:
  AD: ANDORRA  
  AE: UNITED ARAB EMIRATES          
  AF: AFGHANISTAN
  AG: ANTIGUA & BARBUDA
  AI: ANGUILLA
  AL: ALBANIA  
  AM: ARMENIA  
  AN: NETHERLANDS ANTILLES          
  AO: ANGOLA   
  AR: ARGENTINA
  AS: SAMOA, AMERICAN
  AT: AUSTRIA  
  AU: AUSTRALIA
  AW: ARUBA    
  AZ: AZERBAIJAN                    
  BA: BOSNIA-HERCEGOVINA            
  BB: BARBADOS 
  BD: BANGLADESH                    
  BE: BELGIUM
  BF: BURKINA FASO                  
  BG: BULGARIA 
  BH: BAHRAIN  
  BI: BURUNDI  
  BJ: BENIN    
  BM: BERMUDA  
  BN: BRUNEI   
  BO: BOLIVIA  
  BR: BRAZIL   
  BS: BAHAMAS  
  BT: BHUTAN   
  BW: BOTSWANA 
  BY: BELARUS  
  BZ: BELIZE   
  CA: CANADA   
  CC: COCOS (KEELING) ISLANDS       
  CF: CENTRAL AFRICAN REPUBLIC      
  CG: CONGO    
  CH: SWITZERLAND                   
  CI: IVORY COAST                   
  CK: COOK ISLANDS                  
  CL: CHILE    
  CM: CAMEROON 
  CN: CHINA (MAINLAND)              
  CO: COLOMBIA 
  CR: COSTA RICA                    
  CU: CUBA     
  CV: CAPE VERDE                    
  CX: CHRISTMAS ISLAND(INDIAN OCEAN)
  CY: CYPRUS   
  CZ: CZECH REPUBLIC                
  DE: GERMANY, FED. REPUBLIC
  DJ: DJIBOUTI 
  DK: DENMARK  
  DM: DOMINICA 
  DO: DOMINICAN REPUBLIC            
  DZ: ALGERIA  
  EC: ECUADOR  
  EE: ESTONIA  
  EG: EGYPT    
  EH: WESTERN SAHARA                
  ER: ERITREA  
  ES: SPAIN    
  ET: ETHIOPIA 
  FI: FINLAND  
  FJ: FIJI     
  FK: FALKLAND ISLANDS              
  FL: FISHER LAND                   
  FM: MICRONESIA, FEDERATED STATES
  FO: FAROE ISLANDS                 
  FR: FRANCE   
  GA: GABON    
  GB: GREAT BRITAIN, UNITED KINGDOM, ENGLAND,SCOT
  GD: GRENADA  
  GE: GEORGIA  
  GF: FRENCH GUIANA                 
  GH: GHANA    
  GI: GIBRALTAR
  GL: GREENLAND
  GM: THE GAMBIA                    
  GN: GUINEA   
  GP: GUADELOUPE                    
  GQ: EQUATORIAL GUINEA             
  GR: GREECE   
  GT: GUATEMALA
  GU: GUAM     
  GW: GUINEA-BISSAU                 
  GY: GUYANA   
  GZ: GAZA STRIP                    
  HK: HONG KONG
  HM: HEARD AND MCDONALD ISLANDS    
  HN: HONDURAS 
  HR: CROATIA  
  HT: HAITI    
  HU: HUNGARY  
  ID: INDONESIA
  IE: IRELAND  
  IL: ISRAEL   
  IN: INDIA    
  IO: BRITISH INDIAN OCEAN TERRITORY
  IQ: IRAQ     
  IR: IRAN     
  IS: ICELAND  
  IT: ITALY    
  JM: JAMAICA  
  JO: JORDAN   
  JP: JAPAN    
  KE: KENYA    
  KG: KYRGYZSTAN                    
  KH: CAMBODIA 
  KI: KIRIBATI 
  KM: COMOROS  
  KN: ST. KITTS-NEVIS
  KP: NORTH KOREA                   
  KR: SOUTH KOREA                   
  KW: KUWAIT   
  KY: CAYMAN ISLANDS                
  KZ: KAZAKHSTAN                    
  LA: LAOS     
  LB: LEBANON  
  LC: ST. LUCIA
  LI: LIECHTENSTEIN                 
  LK: SRI LANKA
  LR: LIBERIA  
  LS: LESOTHO  
  LT: LITHUANIA
  LU: LUXEMBOURG                    
  LV: LATVIA   
  LY: LIBYA    
  MA: MOROCCO  
  MC: MONACO   
  MD: MOLDOVA  
  MG: MADAGASCAR (MALAGASY)         
  MH: MARSHALL ISLANDS              
  MK: MACEDONIA (SKOPJE)            
  ML: MALI     
  MM: MYANMAR (BURMA)               
  MN: MONGOLIA 
  MO: MACAO (MACAU)                 
  MP: Mariana Islands
  MQ: MARTINIQUE                    
  MR: MAURITANIA                    
  MS: MONTSERRAT                    
  MT: MALTA AND GOZO                
  MU: MAURITIUS
  MV: MALDIVES 
  MW: MALAWI   
  MX: MEXICO   
  MY: MALAYSIA 
  MZ: MOZAMBIQUE                    
  NA: NAMIBIA  
  NC: NEW CALEDONIA                 
  NE: NIGER    
  NF: NORFOLK ISLAND                
  NG: NIGERIA  
  NI: NICARAGUA
  NL: NETHERLANDS                   
  NO: NORWAY   
  NP: NEPAL    
  NR: NAURU    
  NU: NIUE     
  NZ: NEW ZEALAND                   
  OM: OMAN     
  PA: PANAMA   
  PE: PERU     
  PF: FRENCH POLYNESIA              
  PG: PAPUA NEW GUINEA              
  PH: PHILIPPINES                   
  PK: PAKISTAN 
  PL: POLAND   
  PM: ST PIERRE AND MIQUELON        
  PN: PITCAIRN ISLAND               
  PR: PUERTO RICO                   
  PT: PORTUGAL 
  PW: PALAU    
  PY: PARAGUAY 
  QA: QATAR    
  RE: REUNION (ISLAND, FRENCH)
  RO: ROMANIA  
  RU: RUSSIA   
  RW: RWANDA   
  SA: SAUDI ARABIA                  
  SB: SOLOMON ISLANDS               
  SC: SEYCHELLES                    
  SD: SUDAN    
  SE: SWEDEN   
  SG: SINGAPORE
  SH: ST HELENA
  SI: SLOVENIA 
  SJ: SVALBARD AND JAN MAYEN ISLAND
  SK: SLOVAKIA 
  SL: SIERRA LEONE                  
  SM: SAN MARINO                    
  SN: SENEGAL  
  SO: SOMALIA  
  SR: SURINAME 
  ST: SAO TOME AND PRINCIPE         
  SV: EL SALVADOR                   
  SY: SYRIA    
  SZ: SWAZILAND
  TC: TURKS AND CAICOS ISLANDS      
  TD: CHAD     
  TF: FR SOUTHERN & ANTARCTIC LANDS
  TG: TOGO     
  TH: THAILAND 
  TJ: TAJIKISTAN                    
  TK: TOKELAU ISLANDS               
  TM: TURKMENISTAN                  
  TN: TUNISIA  
  TO: TONGA    
  TP: EAST TIMOR                    
  TR: TURKEY   
  TT: TRINIDAD AND TOBAGO           
  TV: TUVALU   
  TW: CHINA (TAIWAN)                
  TZ: TANZANIA