descartes_wt:
  DIS: DLY
  AWD: ALC
  AWR: IDC
  NFD: AR2
  ARR: AR1
  BKD: RT5
  CCD: CRC
  TRM: TND
  MAN: RTC
  DLV: AR3
  DDL: DEL
  RCF: REC
  RCS: RT2
  RCT: REC
  TFD: ITT
  PRE: TR4
  CRC: CUS
  TGC: HLD
  DEP: TR5
  OSI: MIS
wt_status:
  DLY: Shipment_Delayed
  ALC: Alert_Onfirmed
  IDC: All_Import_Documents_Received
  AR1: Arrived_Dest_Terminal
  RT5: Booked_with_carrier 
  CRC: Customs_Released/Cleared
  TND: Tendered_to_Carrier
  RTC: Routing_Confirmed
  AR2: On_hand_-_Dest_terminal
  AR3: Recovered_-_Dest_Terminal
  DEL: Delivered_w/Proof_of_Delivery
  REC: Recovered_Dest_Terminal
  RT2: Picked_up_from_Shipper
  REC: Recovered_Dest_Terminal
  ITT: In_Transit
  TR4: Assigned_to_flight
  CUS: In_Customs_Clearance
  HLD: Shipment_on_Hold
  TR5: Confirmed_On_Board_Carrier
  MIS: Missing_EDI_Translation_Code
carrier:
  "053": DUBFMEI
  "555": CHACSSU
  "870": IEVFMVV
  "014": YULFMAC
  "999": QIFFMCA
  "057": QVIFMAF
  "098": BOMFMAI
  "643": MLAFMKM
  "029": QIFFMMK
  "086": QIFFMNZ
  "656": QIFFMPX
  "047": LISFMTP
  "027": SEACPAS
  "055": ALLFMAZ
  "205": TYOFMNH
  "001": HDQFMAA
  "090": QIFFMAN
  "988": SELFMOZ
  "257": VIEFMOS
  "196": QIFFMLZ
  "997": QIFFMBG
  "125": LONFMBA
  "236": LHRFIBD
  "106": QIFFMBW
  "700": TLVCL5C
  "172": LUXXUCV
  "160": HDQFMCX
  "297": TPEFMCI
  "781": SHABGCK
  "005": HDQFMCO
  "005": MIAFMCO
  "048": QIFFMCY
  "064": QIFFMOK
  "006": HDQFMDL
  "043": HDQFMCX
  "077": QIFFMMS
  "114": TLVAFLY
  "176": DXBFMEK
  "071": QIFFMET
  "607": AUHFMEY
  "071": CHACSET
  "695": TPEFMBR
  "023": HDQFMFX
  "105": HELFMAY
  "126": QIFFMGA
  "072": QIFFMGF
  "075": QLMFMIB
  "108": QIFFMFI
  "096": QIFFMIR
  "234": QIFFMJD
  "131": TYOFMJL
  "074": AMSFMKL
  "180": SELFMKE
  "229": QIFFMKU
  "045": SCLFRLA
  "231": VIEFMOS
  "020": FRAFMLH
  "232": KULFMMH
  "182": QIFFMMA
  "129": SPLAEMP
  "933": TYOFMKZ
  "050": QIFFMOA
  "214": QIFFMPK
  "079": QIFFMPR
  "403": MSPFMPO
  "080": CHACSLO
  "081": SYDFMQF
  "157": QIFFMQR
  "147": QVIFMAT
  "672": QIFFMBI
  "512": AMMFXRJ
  "117": CPHBGSK
  "065": QIFFMSV
  "629": SINFMSQ
  "618": SINFMSQ
  "083": JNBFMSA
  "724": ZRHFMLX
  "070": QIFFMRB
  "202": QIFFMTA
  "217": BKKFMTG
  "270": QIFFMTL
  "235": ISTFMTK
  "566": QIFFMPS
  "016": CHICPXH
  "406": MSPFM5X
  "037": HDQFMUS
  "183": QIFFMRG
  "738": QIFFMVN
  "932": LONFMVS
  "115": QIFFMJU
