carrier:
  "053": DUBFMEI
  "555": CHACSSU
  "870": IEVFMVV
  "014": YULFMAC
  "999": QIFFMCA
  "057": QVIFMAF
  "098": BOMFMAI
  "643": MLAFMKM
  "029": QIFFMMK
  "086": QIFFMNZ
  "656": QIFFMPX
  "047": LISFMTP
  "027": SEACPAS
  "055": ALLFMAZ
  "205": TYOFMNH
  "001": HDQFMAA
  "090": QIFFMAN
  "988": SELFMOZ
  "257": VIEFMOS
  "196": QIFFMLZ
  "997": QIFFMBG
  "125": LONFMBA
  "236": LHRFIBD
  "106": QIFFMBW
  "700": TLVCL5C
  "172": LUXXUCV
  "160": HDQFMCX
  "297": TPEFMCI
  "781": SHABGCK
  "005": HDQFMCO
  "005": MIAFMCO
  "048": QIFFMCY
  "064": QIFFMOK
  "006": HDQFMDL
  "043": HDQFMCX
  "077": QIFFMMS
  "114": TLVAFLY
  "176": DXBFMEK
  "071": QIFFMET
  "607": AUHFMEY
  "071": CHACSET
  "695": TPEFMBR
  "023": HDQFMFX
  "105": HELFMAY
  "126": QIFFMGA
  "072": QIFFMGF
  "075": QLMFMIB
  "108": QIFFMFI
  "096": QIFFMIR
  "234": QIFFMJD
  "131": TYOFMJL
  "074": AMSFMKL
  "180": SELFMKE
  "229": QIFFMKU
  "045": SCLFRLA
  "231": VIEFMOS
  "020": FRAFMLH
  "232": KULFMMH
  "182": QIFFMMA
  "129": SPLAEMP
  "933": TYOFMKZ
  "050": QIFFMOA
  "214": QIFFMPK
  "079": QIFFMPR
  "403": MSPFMPO
  "080": CHACSLO
  "081": SYDFMQF
  "157": QIFFMQR
  "147": QVIFMAT
  "672": QIFFMBI
  "512": AMMFXRJ
  "117": CPHBGSK
  "065": QIFFMSV
  "629": SINFMSQ
  "618": SINFMSQ
  "083": JNBFMSA
  "724": ZRHFMLX
  "070": QIFFMRB
  "202": QIFFMTA
  "217": BKKFMTG
  "270": QIFFMTL
  "235": ISTFMTK
  "566": QIFFMPS
  "016": CHICPXH
  "406": MSPFM5X
  "037": HDQFMUS
  "183": QIFFMRG
  "738": QIFFMVN
  "932": LONFMVS
  "115": QIFFMJU